AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false
